# Generated by Django 3.1.2 on 2020-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('assessment', models.CharField(max_length=200, null=True)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('grade_and_class', models.CharField(max_length=200, null=True)),
                ('subjects', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
