# Generated by Django 3.1.2 on 2020-11-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grades',
            new_name='grade',
        ),
    ]
