# Generated by Django 3.1.2 on 2020-11-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20201109_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('assessment', models.CharField(max_length=200, null=True)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('assessment', models.CharField(max_length=200, null=True)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='religous_studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('assessment', models.CharField(max_length=200, null=True)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('assessment', models.CharField(max_length=200, null=True)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='grade',
            new_name='art',
        ),
    ]
