# Generated by Django 3.1.2 on 2020-11-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20201109_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='geography',
            new_name='geographie',
        ),
        migrations.RenameModel(
            old_name='religous_studies',
            new_name='religous_studie',
        ),
    ]
