# Generated by Django 3.1.2 on 2020-11-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20201109_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='assessment_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='geographie',
            name='assessment_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='assessment_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='religous_studie',
            name='assessment_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='science',
            name='assessment_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='subjects',
            field=models.ManyToManyField(to='school.subject'),
        ),
    ]
