# Generated by Django 3.1.2 on 2020-11-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20201109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='student_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='geographie',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='geographie',
            name='student_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='math',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='math',
            name='student_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='religous_studie',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='religous_studie',
            name='student_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='student_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
