# Generated by Django 3.1.2 on 2020-11-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20201109_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_profile',
        ),
    ]
