# Generated by Django 3.1.2 on 2020-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_delete_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('grade_and_class', models.CharField(max_length=200, null=True)),
                ('subjects', models.ManyToManyField(to='school.subject')),
            ],
        ),
    ]
