# Generated by Django 3.1.2 on 2020-11-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='student_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
