# Generated by Django 3.1.2 on 2020-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_student_profile_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
