# Generated by Django 3.1.2 on 2020-11-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20201109_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographie',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student_profile'),
        ),
    ]
