# Generated by Django 3.1.2 on 2020-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20201109_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='student_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
