# Generated by Django 3.1.2 on 2020-11-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20201109_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student_profile'),
        ),
        migrations.AlterField(
            model_name='math',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student_profile'),
        ),
        migrations.AlterField(
            model_name='religous_studie',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student_profile'),
        ),
        migrations.AlterField(
            model_name='science',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student_profile'),
        ),
    ]
